### PR TITLE
Feedback based on DWX

### PR DESCRIPTION
**Pull request by IObert**

### CODE REVIEW

**Comment by IObert** [comment]
Thanks for merging
I just tested this branch on the other laptop and it somehow didn't work there (black screen when I want to start the extension). I tried to reset the source code there and still got the same error, so it might not even be related to these changes. 

But just to be sure, can you try to pull the changes and see if the custom mission starts for you?

**Comment by nokenwa** [comment]
Will do in a couple hours. On a train at the moment

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by nokenwa** [comment]
Hmm, Worked on my machine.

**Comment by nokenwa** [comment]
Any logs or anything I can take a look at?

**Pull request merged**
